org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
loom.ignoreDependencyLoomVersionValidation=true

project.isolated=true
project.libs=26.2-SNAPSHOT
project.platforms=Common, Fabric, NeoForge
project.plugins=1.1-SNAPSHOT

mod.authors=Fuzs
mod.description=Deleted worlds are gone forever, right? Not anymore! Simply restore them from your recycle bin.
mod.group=fuzs.deleteworldstotrash
mod.id=deleteworldstotrash
mod.license=MPL-2.0
mod.name=Delete Worlds To Trash
mod.version=26.2.0

distributions.curseforge.id=571076
distributions.curseforge.slug=delete-worlds-to-trash
distributions.github.slug=delete-worlds-to-trash
distributions.modrinth.id=7diJQfvM
distributions.modrinth.slug=delete-worlds-to-trash

environments.client=required
environments.server=unsupported
